### ISSUE TITLE
Error: Cannot find module './lib/config'

### ISSUE THREAD

**Issue by lanselambor** [girliemac/RPi-KittyCam#5]
The error comes out because of missing "config.js" in RPi-KittyCam/node_modules/cloudinary/lib/ 

People can download the file from this repository: https://github.com/cloudinary/cloudinary_npm/blob/master/lib/config.js

**Comment by girliemac** [comment]
You may want to just delete the cloudinary module under `/node_modules`, and freshly install one with npm.  

`$ npm install cloudinary`

**Comment by lanselambor** [comment]
It was failed to execute "npm install cloundinary" last night, but it works now. 
It's weird.

**Comment by girliemac** [comment]
Yeah, it happens sometimes!
