### ISSUE TITLE
Any updates on a Step by Step Tutorial?

### ISSUE THREAD

**Issue by grenade44** [girliemac/RPi-KittyCam#6]
Hi, I really like the idea of this but i cant seem to work out how to install this onto my RP2 running Jessie.
i finally got node_latest_armhf.deb to install but now have issues with kittydar.

pi@raspberrypi:~/RPi-KittyCam $ npm install kittydar —save
npm WARN package.json KittyCam@1.0.0 No repository field.
npm ERR! addLocal Could not install /home/pi/RPi-KittyCam/—save
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "kittydar" "—save"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /home/pi/RPi-KittyCam/—save
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/RPi-KittyCam/—save'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/RPi-KittyCam/npm-debug.log

Any help would be great. Thanks

**Comment by fosskers** [comment]
Yes, a tutorial would be great. I want to get this running for my cat.

**Comment by girliemac** [comment]
There may be many different issues (I had a lot of trouble with node-canvas and kittydar initially), but first thing came to mind is node.js version.

I am not sure exactly which version of node that node_latest_armhf.deb gets, but you may want o downgrade the node to 0.12.x.
http://node-arm.herokuapp.com/

I am guessing the dependencies may not work with the latest node, or anything after when node.js merged with io.js, (when node version jumped to 4.0 from 0.12.x).

**Comment by girliemac** [comment]
Ta-da!
I FINALLY finish writing the blog :-D
http://www.girliemac.com/blog/2015/12/25/kittycam-raspberrypi-camera-cat-face-recog-nodejs/

**Comment by girliemac** [comment]
I upgraded a hardware (from Pi 2 to Pi 3) and software (Node 0.12 to 4, and updated all dependencies). I will update readme and/or my blog soon!

**Comment by girliemac** [comment]
Update for Pi 3: http://www.girliemac.com/blog/2016/06/13/kittycam-update-with-raspberrypi3/
