### ISSUE TITLE
Need to install WiringPi

### ISSUE THREAD

**Issue by vinceallenvince** [girliemac/RPi-KittyCam#7]
After following the step by step instructions, I received the following error. I believe it's coming from raspi-io.

error: libwiringPi.so: cannot open shared object file: No such file or directory

To resolve I followed the steps to install WiringPi here.

https://projects.drogon.net/raspberry-pi/wiringpi/download-and-install/

And it works!

http://res.cloudinary.com/vinceallenvince/image/upload/v1452104649/lonw9e9qrwhw0x0poo84.png

**Comment by girliemac** [comment]
Sorry for not noticing this issue for months! ugh my bad.
It looks like the newer Raspbian Jesse comes with WiringPi preinstalled. So this issue doesn't happen anymore!
